Verify checksum

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,51 +1,91 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
+shopt -s inherit_errexit 2>/dev/null || true
 
 [[ -z ${ASDF_INSTALL_TYPE+x} ]] && echo "ASDF_INSTALL_TYPE is required" && exit 1
 [[ -z ${ASDF_INSTALL_VERSION+x} ]] && echo "ASDF_INSTALL_VERSION is required" && exit 1
 [[ -z ${ASDF_INSTALL_PATH+x} ]] && echo "ASDF_INSTALL_PATH is required" && exit 1
 
-install() {
-	local install_type=$1
-	[[ ${install_type} != "version" ]] && echo "intall type, ${install_type}, is not supported" && exit 1
+function gh_curl() {
+	if [[ -n ${GITHUB_TOKEN-} ]]; then
+		curl -fLsS -H "Authorization: token ${GITHUB_TOKEN}" "$@"
+	elif [[ -n ${GITHUB_API_TOKEN-} ]]; then
+		curl -fLsS -H "Authorization: token ${GITHUB_API_TOKEN}" "$@"
+	else
+		curl -fLsS "$@"
+	fi
+}
 
+function install() {
+	# set -x
+	local install_type=$1
+	[[ ${install_type} != "version" ]] && echo "install type, ${install_type}, is not supported" && exit 1
+
+	local prefix="v"
 	local version=$2
 	local install_path=$3
+
+	local tmp_download_dir
+
+	tmp_download_dir=$(mktemp -d -t asdf.XXXXXXXX)
 
 	local bin_install_path="${install_path}/bin"
 
 	local platform
-	platform=$(uname | tr '[:upper:]' '[:lower:]')
+	platform=$(uname -s | tr '[:upper:]' '[:lower:]')
 
 	local arch
 	arch=$(uname -m)
 	case "${arch}" in
-	x86_64) arch="amd64" ;;
-	aarch64) arch="arm64" ;;
+	aarch64) arch=arm64 ;;
+	i?86) arch=386 ;;
+	x86_64) arch=amd64 ;;
 	esac
 
 	local download_url
-	download_url="https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/${version}/${platform}-${arch}/docker-credential-ecr-login"
-
 	local checksum_url
-	checksum_url="${download_url}.sha256"
+
+	local repo="awslabs/amazon-ecr-credential-helper"
+	local download_filename="${platform}-${arch}/docker-credential-ecr-login "
+	local checksum_filename="${download_filename}.sha256"
+
+	if [[ -n ${GITHUB_TOKEN-} ]] || [[ -n ${GITHUB_API_TOKEN-} ]]; then
+		local asset_url
+		asset_url="https://api.github.com/repos/${repo}/releases/tags/${prefix}${version}"
+		download_url=$(gh_curl -H "Accept: application/vnd.github.v3.raw" "${asset_url}" | jq -r ".assets | map(select(.name == \"${download_filename}\"))[0].url")
+		if [[ ${download_url} == null ]]; then
+			echo "Asset ${download_filename} not found in a release ${prefix}${version}."
+			exit 1
+		fi
+		checksum_url=$(gh_curl -H "Accept: application/vnd.github.v3.raw" "${asset_url}" | jq -r ".assets | map(select(.name == \"${checksum_filename}\"))[0].url")
+		if [[ ${checksum_url} == null ]]; then
+			echo "Asset ${checksum_filename} not found in a release ${prefix}${version}."
+			exit 1
+		fi
+	else
+		download_url="https://github.com/${repo}/releases/download/${prefix}${version}/${download_filename}"
+		checksum_url="https://github.com/${repo}/releases/download/${prefix}${version}/${checksum_filename}"
+	fi
+
+	echo "Downloading ${download_filename} from release ${prefix}${version} from ${download_url}"
+
+	mkdir -p "${tmp_download_dir}"
+
+	pushd "${tmp_download_dir}" >/dev/null
+
+	gh_curl -H "Accept: application/octet-stream" -o docker-credential-ecr-login "${download_url}"
+
+	if command -v shasum >/dev/null; then
+		gh_curl -H "Accept: application/octet-stream" "${checksum_url}" | awk '$2 == "amazon-ecr-credential-helper" {print}' | shasum -a 256 -c
+	elif command -v sha256sum >/dev/null; then
+		gh_curl -H "Accept: application/octet-stream" "${checksum_url}" | awk '$2 == "amazon-ecr-credential-helper" {print}' | sha256sum -c
+	fi
 
 	mkdir -p "${bin_install_path}"
 
-	echo "Downloading amazon-ecr-credential-helper from ${download_url}"
-
-	pushd "${bin_install_path}" >/dev/null
-
-	curl -sL "${download_url}" -o "${bin_install_path}/docker-credential-ecr-login"
-
-	if command -v shasum >/dev/null; then
-		curl -sL "${checksum_url}" | shasum -a 256 -c
-	elif command -v sha256sum; then
-		curl -sL "${checksum_url}" | sha256sum -c
-	fi
-
-	chmod +x "${bin_install_path}/docker-credential-ecr-login"
+	chmod +x amazon-ecr-credential-helper
+	cp -fp amazon-ecr-credential-helper "${bin_install_path}/docker-credential-ecr-login"
 
 	popd >/dev/null
 }
